---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: prefect-server
    prefect-version: {{ .Chart.AppVersion }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.prefect-server.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.prefect-server.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.prefect-server.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.prefect-server.service.type }}
  {{- if and .Values.prefect-server.service.clusterIP (eq .Values.prefect-server.service.type "ClusterIP") }}
  clusterIP: {{ .Values.prefect-server.service.clusterIP }}
  {{- end }}
  {{- if eq .Values.prefect-server.service.type "NodePort" }}
  externalTrafficPolicy: {{ .Values.prefect-server.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: server-svc-port
      port: {{ .Values.prefect-server.service.port }}
      protocol: TCP
      targetPort: {{ .Values.prefect-server.service.targetPort }}
      {{- if and (or (eq .Values.prefect-server.service.type "NodePort") (eq .Values.prefect-server.service.type "LoadBalancer")) (not (empty .Values.prefect-server.service.nodePort)) }}
      nodePort: {{ .Values.prefect-server.service.nodePort }}
      {{- else if eq .Values.prefect-server.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- range .Values.prefect-server.service.extraPorts }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if and (eq $.Values.prefect-server.service.type "NodePort") (not (empty .nodePort)) }}
      nodePort: {{ .nodePort }}
      {{- else if eq $.Values.prefect-server.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: server